// Copyright (2019) Cobalt Speech and Language, Inc.

#ifndef CUBICEXCEPTION_H
#define CUBICEXCEPTION_H

#include <exception>
#include <string>

#include <grpcpp/grpcpp.h>

//! CubicException represents an error generated by the Cubic
//! client.
class CubicException : public std::exception
{
public:
    CubicException(const std::string &msg);
    CubicException(const grpc::Status &status);
    ~CubicException() override;
    const char *what() const noexcept override;

private:
    std::string mMsg;
};

#endif // CUBICEXCEPTION_H
