# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cubic-demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  

  # Pods for cubic-demo

  target 'sdk-cubic' do
    pod 'SwiftProtobuf', '~> 1.0'
    pod 'SwiftGRPC'
    # Pods for testing
  end


end
