relativeURLs = true

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Cubic SDK -- Cobalt"
pygmentsCodeFences = true
pygmentsStyle = "native"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

[params]
showVisitedLinks = true # default is false
themeStyle = "original" # "original" or "flex" # default "flex"
themeVariant = "blue" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = false # set true to open shortcuts links to a new tab/window
enableGitInfo = false

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> <label>Github repo</label>"
identifier = "gh"
url = "https://github.com/cobaltspeech/sdk-cubic"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> <label>Contact us</label>"
identifier = "contactus"
url = "https://www.cobaltspeech.com/contact"
weight = 20

[markup.goldmark.renderer]
unsafe= true

[module]
[[module.imports]]
    path = "github.com/cobaltspeech/docdock"
    # Project theme
