// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cubic.proto

package cubicpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The encoding of the audio data to be sent for recognition.
//
// For best results, the audio source should be captured and transmitted using
// the RAW_LINEAR16 encoding.
type RecognitionConfig_Encoding int32

const (
	// Raw (headerless) Uncompressed 16-bit signed little endian samples (linear
	// PCM), single channel, sampled at the rate expected by the chosen `Model`.
	RecognitionConfig_RAW_LINEAR16 RecognitionConfig_Encoding = 0
	// WAV (data with RIFF headers), with data sampled at a rate equal to or
	// higher than the sample rate expected by the chosen Model.
	RecognitionConfig_WAV RecognitionConfig_Encoding = 1
	// MP3 data, sampled at a rate equal to or higher than the sampling rate
	// expected by the chosen Model.
	RecognitionConfig_MP3 RecognitionConfig_Encoding = 2
	// FLAC data, sampled at a rate equal to or higher than the sample rate
	// expected by the chosen Model.
	RecognitionConfig_FLAC RecognitionConfig_Encoding = 3
	// VOX data (Dialogic ADPCM), sampled at 8 KHz.
	RecognitionConfig_VOX8000 RecognitionConfig_Encoding = 4
	// μ-law (8-bit) encoded RAW data, single channel, sampled at 8 KHz.
	RecognitionConfig_ULAW8000 RecognitionConfig_Encoding = 5
)

var RecognitionConfig_Encoding_name = map[int32]string{
	0: "RAW_LINEAR16",
	1: "WAV",
	2: "MP3",
	3: "FLAC",
	4: "VOX8000",
	5: "ULAW8000",
}

var RecognitionConfig_Encoding_value = map[string]int32{
	"RAW_LINEAR16": 0,
	"WAV":          1,
	"MP3":          2,
	"FLAC":         3,
	"VOX8000":      4,
	"ULAW8000":     5,
}

func (x RecognitionConfig_Encoding) String() string {
	return proto.EnumName(RecognitionConfig_Encoding_name, int32(x))
}

func (RecognitionConfig_Encoding) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_82ad8c6e2ec8aa3b, []int{8, 0}
}

// The top-level message sent by the client for the `ListModels` method.
type ListModelsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListModelsRequest) Reset()         { *m = ListModelsRequest{} }
func (m *ListModelsRequest) String() string { return proto.CompactTextString(m) }
func (*ListModelsRequest) ProtoMessage()    {}
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82ad8c6e2ec8aa3b, []int{0}
}

func (m *ListModelsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListModelsRequest.Unmarshal(m, b)
}
func (m *ListModelsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListModelsRequest.Marshal(b, m, deterministic)
}
func (m *ListModelsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListModelsRequest.Merge(m, src)
}
func (m *ListModelsRequest) XXX_Size() int {
	return xxx_messageInfo_ListModelsRequest.Size(m)
}
func (m *ListModelsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListModelsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListModelsRequest proto.InternalMessageInfo

// The top-level message sent by the client for the `Recognize` method.  Both
// the `RecognitionConfig` and `RecognitionAudio` fields are required.  The
// entire audio data must be sent in one request.  If your audio data is larger,
// please use the `StreamingRecognize` call..
type RecognizeRequest struct {
	// Provides configuration to create the recognizer.
	Config *RecognitionConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// The audio data to be recognized
	Audio                *RecognitionAudio `protobuf:"bytes,2,opt,name=audio,proto3" json:"audio,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RecognizeRequest) Reset()         { *m = RecognizeRequest{} }
func (m *RecognizeRequest) String() string { return proto.CompactTextString(m) }
func (*RecognizeRequest) ProtoMessage()    {}
func (*RecognizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82ad8c6e2ec8aa3b, []int{1}
}

func (m *RecognizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecognizeRequest.Unmarshal(m, b)
}
func (m *RecognizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecognizeRequest.Marshal(b, m, deterministic)
}
func (m *RecognizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecognizeRequest.Merge(m, src)
}
func (m *RecognizeRequest) XXX_Size() int {
	return xxx_messageInfo_RecognizeRequest.Size(m)
}
func (m *RecognizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecognizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecognizeRequest proto.InternalMessageInfo

func (m *RecognizeRequest) GetConfig() *RecognitionConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *RecognizeRequest) GetAudio() *RecognitionAudio {
	if m != nil {
		return m.Audio
	}
	return nil
}

// The top-level message sent by the client for the `StreamingRecognize`
// request.  Multiple `StreamingRecognizeRequest` messages are sent. The first
// message must contain a `RecognitionConfig` message only, and all subsequent
// messages must contain `RecognitionAudio` only.  All `RecognitionAudio`
// messages must contain non-empty audio.  If audio content is empty, the server
// may interpret it as end of stream and stop accepting any further messages.
type StreamingRecognizeRequest struct {
	// Types that are valid to be assigned to Request:
	//	*StreamingRecognizeRequest_Config
	//	*StreamingRecognizeRequest_Audio
	Request              isStreamingRecognizeRequest_Request `protobuf_oneof:"request"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *StreamingRecognizeRequest) Reset()         { *m = StreamingRecognizeRequest{} }
func (m *StreamingRecognizeRequest) String() string { return proto.CompactTextString(m) }
func (*StreamingRecognizeRequest) ProtoMessage()    {}
func (*StreamingRecognizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82ad8c6e2ec8aa3b, []int{2}
}

func (m *StreamingRecognizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingRecognizeRequest.Unmarshal(m, b)
}
func (m *StreamingRecognizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingRecognizeRequest.Marshal(b, m, deterministic)
}
func (m *StreamingRecognizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingRecognizeRequest.Merge(m, src)
}
func (m *StreamingRecognizeRequest) XXX_Size() int {
	return xxx_messageInfo_StreamingRecognizeRequest.Size(m)
}
func (m *StreamingRecognizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingRecognizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingRecognizeRequest proto.InternalMessageInfo

type isStreamingRecognizeRequest_Request interface {
	isStreamingRecognizeRequest_Request()
}

type StreamingRecognizeRequest_Config struct {
	Config *RecognitionConfig `protobuf:"bytes,1,opt,name=config,proto3,oneof"`
}

type StreamingRecognizeRequest_Audio struct {
	Audio *RecognitionAudio `protobuf:"bytes,2,opt,name=audio,proto3,oneof"`
}

func (*StreamingRecognizeRequest_Config) isStreamingRecognizeRequest_Request() {}

func (*StreamingRecognizeRequest_Audio) isStreamingRecognizeRequest_Request() {}

func (m *StreamingRecognizeRequest) GetRequest() isStreamingRecognizeRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *StreamingRecognizeRequest) GetConfig() *RecognitionConfig {
	if x, ok := m.GetRequest().(*StreamingRecognizeRequest_Config); ok {
		return x.Config
	}
	return nil
}

func (m *StreamingRecognizeRequest) GetAudio() *RecognitionAudio {
	if x, ok := m.GetRequest().(*StreamingRecognizeRequest_Audio); ok {
		return x.Audio
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StreamingRecognizeRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StreamingRecognizeRequest_Config)(nil),
		(*StreamingRecognizeRequest_Audio)(nil),
	}
}

// The top-level message sent by the client for the `CompileContext` request. It
// contains a list of phrases or words, paired with a context token allowed by
// the model being used. The token specifies a category such as "names",
// "airports", "contacts", "product_name" etc. The context token is used to
// determine the position in the recognition output where the provided list of
// phrases or words may appear. The allowed context tokens for a given model can
// be found in its ModelAttributes obtained via the `ListModels` method.
type CompileContextRequest struct {
	// Unique identifier of the model to compile the context information for.
	ModelId string `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// The token that is associated with the provided list of phrases or words
	// (e.g "names", "airports" etc.). Must be from one of the allowed tokens in
	// the model being used.
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// List of phrases and/or words to be compiled.
	Phrases              []*ContextPhrase `protobuf:"bytes,3,rep,name=phrases,proto3" json:"phrases,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CompileContextRequest) Reset()         { *m = CompileContextRequest{} }
func (m *CompileContextRequest) String() string { return proto.CompactTextString(m) }
func (*CompileContextRequest) ProtoMessage()    {}
func (*CompileContextRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82ad8c6e2ec8aa3b, []int{3}
}

func (m *CompileContextRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompileContextRequest.Unmarshal(m, b)
}
func (m *CompileContextRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompileContextRequest.Marshal(b, m, deterministic)
}
func (m *CompileContextRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompileContextRequest.Merge(m, src)
}
func (m *CompileContextRequest) XXX_Size() int {
	return xxx_messageInfo_CompileContextRequest.Size(m)
}
func (m *CompileContextRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CompileContextRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CompileContextRequest proto.InternalMessageInfo

func (m *CompileContextRequest) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

func (m *CompileContextRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CompileContextRequest) GetPhrases() []*ContextPhrase {
	if m != nil {
		return m.Phrases
	}
	return nil
}

// The message sent by the server for the `Version` method.
type VersionResponse struct {
	// version of the cubic library handling the recognition
	Cubic string `protobuf:"bytes,1,opt,name=cubic,proto3" json:"cubic,omitempty"`
	// version of the server handling these requests
	Server               string   `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82ad8c6e2ec8aa3b, []int{4}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetCubic() string {
	if m != nil {
		return m.Cubic
	}
	return ""
}

func (m *VersionResponse) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

// The message returned to the client by the `ListModels` method.
type ListModelsResponse struct {
	// List of models available for use that match the request.
	Models               []*Model `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListModelsResponse) Reset()         { *m = ListModelsResponse{} }
func (m *ListModelsResponse) String() string { return proto.CompactTextString(m) }
func (*ListModelsResponse) ProtoMessage()    {}
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82ad8c6e2ec8aa3b, []int{5}
}

func (m *ListModelsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListModelsResponse.Unmarshal(m, b)
}
func (m *ListModelsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListModelsResponse.Marshal(b, m, deterministic)
}
func (m *ListModelsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListModelsResponse.Merge(m, src)
}
func (m *ListModelsResponse) XXX_Size() int {
	return xxx_messageInfo_ListModelsResponse.Size(m)
}
func (m *ListModelsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListModelsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListModelsResponse proto.InternalMessageInfo

func (m *ListModelsResponse) GetModels() []*Model {
	if m != nil {
		return m.Models
	}
	return nil
}

// Collection of sequence of recognition results in a portion of audio.  When
// transcribing a single audio channel (e.g. RAW_LINEAR16 input, or a mono
// file), results will be ordered chronologically.  When transcribing multiple
// channels, the results of all channels will be interleaved.  Results of each
// individual channel will be chronological.  No such promise is made for the
// ordering of results of different channels, as results are returned for each
// channel individually as soon as they are ready.
type RecognitionResponse struct {
	Results              []*RecognitionResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RecognitionResponse) Reset()         { *m = RecognitionResponse{} }
func (m *RecognitionResponse) String() string { return proto.CompactTextString(m) }
func (*RecognitionResponse) ProtoMessage()    {}
func (*RecognitionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82ad8c6e2ec8aa3b, []int{6}
}

func (m *RecognitionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecognitionResponse.Unmarshal(m, b)
}
func (m *RecognitionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecognitionResponse.Marshal(b, m, deterministic)
}
func (m *RecognitionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecognitionResponse.Merge(m, src)
}
func (m *RecognitionResponse) XXX_Size() int {
	return xxx_messageInfo_RecognitionResponse.Size(m)
}
func (m *RecognitionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RecognitionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RecognitionResponse proto.InternalMessageInfo

func (m *RecognitionResponse) GetResults() []*RecognitionResult {
	if m != nil {
		return m.Results
	}
	return nil
}

// The message returned to the client by the `CompileContext` method.
type CompileContextResponse struct {
	// Context information stored in a compact form that is fast to access for
	// a Cubic model.
	Context              *CompiledContext `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CompileContextResponse) Reset()         { *m = CompileContextResponse{} }
func (m *CompileContextResponse) String() string { return proto.CompactTextString(m) }
func (*CompileContextResponse) ProtoMessage()    {}
func (*CompileContextResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82ad8c6e2ec8aa3b, []int{7}
}

func (m *CompileContextResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompileContextResponse.Unmarshal(m, b)
}
func (m *CompileContextResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompileContextResponse.Marshal(b, m, deterministic)
}
func (m *CompileContextResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompileContextResponse.Merge(m, src)
}
func (m *CompileContextResponse) XXX_Size() int {
	return xxx_messageInfo_CompileContextResponse.Size(m)
}
func (m *CompileContextResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CompileContextResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CompileContextResponse proto.InternalMessageInfo

func (m *CompileContextResponse) GetContext() *CompiledContext {
	if m != nil {
		return m.Context
	}
	return nil
}

// Configuration for setting up a Recognizer
type RecognitionConfig struct {
	// Unique identifier of the model to use, as obtained from a `Model` message.
	ModelId string `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// Encoding of audio data sent/streamed through the `RecognitionAudio`
	// messages.  For encodings like WAV/MP3 that have headers, the headers are
	// expected to be sent at the beginning of the stream, not in every
	// `RecognitionAudio` message.
	//
	// If not specified, the default encoding is RAW_LINEAR16.
	//
	// Depending on how they are configured, server instances of this service may
	// not support all the encodings enumerated above. They are always required to
	// accept RAW_LINEAR16.  If any other `Encoding` is specified, and it is not
	// available on the server being used, the recognition request will result in
	// an appropriate error message.
	AudioEncoding RecognitionConfig_Encoding `protobuf:"varint,2,opt,name=audio_encoding,json=audioEncoding,proto3,enum=cobaltspeech.cubic.RecognitionConfig_Encoding" json:"audio_encoding,omitempty"`
	// Idle Timeout of the created Recognizer.  If no audio data is received by
	// the recognizer for this duration, ongoing rpc calls will result in an
	// error, the recognizer will be destroyed and thus more audio may not be sent
	// to the same recognizer.  The server may impose a limit on the maximum idle
	// timeout that can be specified, and if the value in this message exceeds
	// that serverside value, creating of the recognizer will fail with an error.
	IdleTimeout *duration.Duration `protobuf:"bytes,3,opt,name=idle_timeout,json=idleTimeout,proto3" json:"idle_timeout,omitempty"`
	// This is an optional field.  If this is set to true, each result will
	// include a list of words and the start time offset (timestamp) and the
	// duration for each of those words.  If set to `false`, no word-level
	// timestamps will be returned.  The default is `false`.
	EnableWordTimeOffsets bool `protobuf:"varint,4,opt,name=enable_word_time_offsets,json=enableWordTimeOffsets,proto3" json:"enable_word_time_offsets,omitempty"`
	// This is an optional field.  If this is set to true, each result will
	// include a list of words and the confidence for those words.  If `false`, no
	// word-level confidence information is returned.  The default is `false`.
	EnableWordConfidence bool `protobuf:"varint,5,opt,name=enable_word_confidence,json=enableWordConfidence,proto3" json:"enable_word_confidence,omitempty"`
	// This is an optional field.  If this is set to true, the field
	// `RecognitionAlternative.raw_transcript` will be populated with the raw
	// transcripts output from the recognizer will be exposed without any
	// formatting rules applied.  If this is set to false, that field will not
	// be set in the results.  The RecognitionAlternative.transcript will
	// always be populated with text formatted according to the server's settings.
	EnableRawTranscript bool `protobuf:"varint,6,opt,name=enable_raw_transcript,json=enableRawTranscript,proto3" json:"enable_raw_transcript,omitempty"`
	// This is an optional field.  If this is set to true, the results will
	// include a confusion network.  If set to `false`, no confusion network will
	// be returned.  The default is `false`.  If the model being used does not
	// support a confusion network, results may be returned without a confusion
	// network available.  If this field is set to `true`, then
	// `enable_raw_transcript` is also forced to be true.
	EnableConfusionNetwork bool `protobuf:"varint,7,opt,name=enable_confusion_network,json=enableConfusionNetwork,proto3" json:"enable_confusion_network,omitempty"`
	// This is an optional field.  If the audio has multiple channels, this field
	// should be configured with the list of channel indices that should be
	// transcribed.  Channels are 0-indexed.
	//
	// Example: `[0]` for a mono file, `[0, 1]` for a stereo file.
	//
	// If this field is not set, a mono file will be assumed by default and only
	// channel-0 will be transcribed even if the file actually has additional
	// channels.
	//
	// Channels that are present in the audio may be omitted, but it is an error
	// to include a channel index in this field that is not present in the audio.
	// Channels may be listed in any order but the same index may not be repeated
	// in this list.
	//
	// BAD: `[0, 2]` for a stereo file; BAD: `[0, 0]` for a mono file.
	AudioChannels []uint32 `protobuf:"varint,8,rep,packed,name=audio_channels,json=audioChannels,proto3" json:"audio_channels,omitempty"`
	// This is an optional field.  If there is any metadata associated with the
	// audio being sent, use this field to provide it to cubic.  The server may
	// record this metadata when processing the request.  The server does not use
	// this field for any other purpose.
	Metadata *RecognitionMetadata `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// This is an optional field. If there is any context information that can aid
	// speech recognition, it may be provided through this field. This can be used
	// to improve the transcription of particular phrases or words such as proper
	// names or commands for example. This can also be used to add out of
	// vocabulary words to the model. Currently, all context information must be
	// pre-compiled via the `CompileContext()` method before sending it with a
	// `Recognizer()` or `StreamingRecognize()` request.
	Context              *RecognitionContext `protobuf:"bytes,10,opt,name=context,proto3" json:"context,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *RecognitionConfig) Reset()         { *m = RecognitionConfig{} }
func (m *RecognitionConfig) String() string { return proto.CompactTextString(m) }
func (*RecognitionConfig) ProtoMessage()    {}
func (*RecognitionConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_82ad8c6e2ec8aa3b, []int{8}
}

func (m *RecognitionConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecognitionConfig.Unmarshal(m, b)
}
func (m *RecognitionConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecognitionConfig.Marshal(b, m, deterministic)
}
func (m *RecognitionConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecognitionConfig.Merge(m, src)
}
func (m *RecognitionConfig) XXX_Size() int {
	return xxx_messageInfo_RecognitionConfig.Size(m)
}
func (m *RecognitionConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RecognitionConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RecognitionConfig proto.InternalMessageInfo

func (m *RecognitionConfig) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

func (m *RecognitionConfig) GetAudioEncoding() RecognitionConfig_Encoding {
	if m != nil {
		return m.AudioEncoding
	}
	return RecognitionConfig_RAW_LINEAR16
}

func (m *RecognitionConfig) GetIdleTimeout() *duration.Duration {
	if m != nil {
		return m.IdleTimeout
	}
	return nil
}

func (m *RecognitionConfig) GetEnableWordTimeOffsets() bool {
	if m != nil {
		return m.EnableWordTimeOffsets
	}
	return false
}

func (m *RecognitionConfig) GetEnableWordConfidence() bool {
	if m != nil {
		return m.EnableWordConfidence
	}
	return false
}

func (m *RecognitionConfig) GetEnableRawTranscript() bool {
	if m != nil {
		return m.EnableRawTranscript
	}
	return false
}

func (m *RecognitionConfig) GetEnableConfusionNetwork() bool {
	if m != nil {
		return m.EnableConfusionNetwork
	}
	return false
}

func (m *RecognitionConfig) GetAudioChannels() []uint32 {
	if m != nil {
		return m.AudioChannels
	}
	return nil
}

func (m *RecognitionConfig) GetMetadata() *RecognitionMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *RecognitionConfig) GetContext() *RecognitionContext {
	if m != nil {
		return m.Context
	}
	return nil
}

// Metadata associated with the audio to be recognized.
type RecognitionMetadata struct {
	// Any custom metadata that the client wants to associate with the recording.
	// This could be a simple string (e.g. a tracing ID) or structured data
	// (e.g. JSON)
	CustomMetadata       string   `protobuf:"bytes,1,opt,name=custom_metadata,json=customMetadata,proto3" json:"custom_metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecognitionMetadata) Reset()         { *m = RecognitionMetadata{} }
func (m *RecognitionMetadata) String() string { return proto.CompactTextString(m) }
func (*RecognitionMetadata) ProtoMessage()    {}
func (*RecognitionMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_82ad8c6e2ec8aa3b, []int{9}
}

func (m *RecognitionMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecognitionMetadata.Unmarshal(m, b)
}
func (m *RecognitionMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecognitionMetadata.Marshal(b, m, deterministic)
}
func (m *RecognitionMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecognitionMetadata.Merge(m, src)
}
func (m *RecognitionMetadata) XXX_Size() int {
	return xxx_messageInfo_RecognitionMetadata.Size(m)
}
func (m *RecognitionMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_RecognitionMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_RecognitionMetadata proto.InternalMessageInfo

func (m *RecognitionMetadata) GetCustomMetadata() string {
	if m != nil {
		return m.CustomMetadata
	}
	return ""
}

// Data that may provide useful context to assist the speech recognition. This
// can be used to improve the transcription of particular phrases or words such
// as proper names or commands for example. This can also be used to add out of
// vocabulary words to the model. We currently support pre-compiled context
// information  via the `CompileContext` method, generated from lists of words
// or phrases expected to appear in the recognition output.
type RecognitionContext struct {
	// List of compiled context information, with each entry being generated from
	// a list of words or phrases expected to appear in the recognition output by
	// the `CompileContext` method.
	Contexts             []*CompiledContext `protobuf:"bytes,1,rep,name=contexts,proto3" json:"contexts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RecognitionContext) Reset()         { *m = RecognitionContext{} }
func (m *RecognitionContext) String() string { return proto.CompactTextString(m) }
func (*RecognitionContext) ProtoMessage()    {}
func (*RecognitionContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_82ad8c6e2ec8aa3b, []int{10}
}

func (m *RecognitionContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecognitionContext.Unmarshal(m, b)
}
func (m *RecognitionContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecognitionContext.Marshal(b, m, deterministic)
}
func (m *RecognitionContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecognitionContext.Merge(m, src)
}
func (m *RecognitionContext) XXX_Size() int {
	return xxx_messageInfo_RecognitionContext.Size(m)
}
func (m *RecognitionContext) XXX_DiscardUnknown() {
	xxx_messageInfo_RecognitionContext.DiscardUnknown(m)
}

var xxx_messageInfo_RecognitionContext proto.InternalMessageInfo

func (m *RecognitionContext) GetContexts() []*CompiledContext {
	if m != nil {
		return m.Contexts
	}
	return nil
}

// Context information stored in a compact form that is fast to access for
// a Cubic model.
type CompiledContext struct {
	// The context information compiled by the `CompileContext` method.
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompiledContext) Reset()         { *m = CompiledContext{} }
func (m *CompiledContext) String() string { return proto.CompactTextString(m) }
func (*CompiledContext) ProtoMessage()    {}
func (*CompiledContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_82ad8c6e2ec8aa3b, []int{11}
}

func (m *CompiledContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompiledContext.Unmarshal(m, b)
}
func (m *CompiledContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompiledContext.Marshal(b, m, deterministic)
}
func (m *CompiledContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompiledContext.Merge(m, src)
}
func (m *CompiledContext) XXX_Size() int {
	return xxx_messageInfo_CompiledContext.Size(m)
}
func (m *CompiledContext) XXX_DiscardUnknown() {
	xxx_messageInfo_CompiledContext.DiscardUnknown(m)
}

var xxx_messageInfo_CompiledContext proto.InternalMessageInfo

func (m *CompiledContext) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// A phrase or word that is to be compiled into context information that can be
// later used to improve speech recognition during a `Recognize` or
// `StreamingRecognize` call. Along with the phrase or word itself, there is an
// optional boost parameter that can be used to boost the likelihood of the
// phrase or word in the recognition output.
type ContextPhrase struct {
	// The actual phrase or word.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// This is an optional field. Higher the number, higher the chances of this
	// phrase or word appearing in the recognition output. The default setting is
	// 0.0, which makes Cubic treat all context phrases or words equally. This
	// setting can be used to differentiate between similar sounding words, with
	// the desired word given a bigger boost value.
	Boost                float32  `protobuf:"fixed32,2,opt,name=boost,proto3" json:"boost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContextPhrase) Reset()         { *m = ContextPhrase{} }
func (m *ContextPhrase) String() string { return proto.CompactTextString(m) }
func (*ContextPhrase) ProtoMessage()    {}
func (*ContextPhrase) Descriptor() ([]byte, []int) {
	return fileDescriptor_82ad8c6e2ec8aa3b, []int{12}
}

func (m *ContextPhrase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContextPhrase.Unmarshal(m, b)
}
func (m *ContextPhrase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContextPhrase.Marshal(b, m, deterministic)
}
func (m *ContextPhrase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContextPhrase.Merge(m, src)
}
func (m *ContextPhrase) XXX_Size() int {
	return xxx_messageInfo_ContextPhrase.Size(m)
}
func (m *ContextPhrase) XXX_DiscardUnknown() {
	xxx_messageInfo_ContextPhrase.DiscardUnknown(m)
}

var xxx_messageInfo_ContextPhrase proto.InternalMessageInfo

func (m *ContextPhrase) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *ContextPhrase) GetBoost() float32 {
	if m != nil {
		return m.Boost
	}
	return 0
}

// Audio to be sent to the recognizer
type RecognitionAudio struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecognitionAudio) Reset()         { *m = RecognitionAudio{} }
func (m *RecognitionAudio) String() string { return proto.CompactTextString(m) }
func (*RecognitionAudio) ProtoMessage()    {}
func (*RecognitionAudio) Descriptor() ([]byte, []int) {
	return fileDescriptor_82ad8c6e2ec8aa3b, []int{13}
}

func (m *RecognitionAudio) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecognitionAudio.Unmarshal(m, b)
}
func (m *RecognitionAudio) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecognitionAudio.Marshal(b, m, deterministic)
}
func (m *RecognitionAudio) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecognitionAudio.Merge(m, src)
}
func (m *RecognitionAudio) XXX_Size() int {
	return xxx_messageInfo_RecognitionAudio.Size(m)
}
func (m *RecognitionAudio) XXX_DiscardUnknown() {
	xxx_messageInfo_RecognitionAudio.DiscardUnknown(m)
}

var xxx_messageInfo_RecognitionAudio proto.InternalMessageInfo

func (m *RecognitionAudio) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// Description of a Cubic Model
type Model struct {
	// Unique identifier of the model.  This identifier is used to choose the
	// model that should be used for recognition, and is specified in the
	// `RecognitionConfig` message.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Model name.  This is a concise name describing the model, and maybe
	// presented to the end-user, for example, to help choose which model to use
	// for their recognition task.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Model attributes
	Attributes           *ModelAttributes `protobuf:"bytes,3,opt,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Model) Reset()         { *m = Model{} }
func (m *Model) String() string { return proto.CompactTextString(m) }
func (*Model) ProtoMessage()    {}
func (*Model) Descriptor() ([]byte, []int) {
	return fileDescriptor_82ad8c6e2ec8aa3b, []int{14}
}

func (m *Model) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Model.Unmarshal(m, b)
}
func (m *Model) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Model.Marshal(b, m, deterministic)
}
func (m *Model) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Model.Merge(m, src)
}
func (m *Model) XXX_Size() int {
	return xxx_messageInfo_Model.Size(m)
}
func (m *Model) XXX_DiscardUnknown() {
	xxx_messageInfo_Model.DiscardUnknown(m)
}

var xxx_messageInfo_Model proto.InternalMessageInfo

func (m *Model) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Model) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Model) GetAttributes() *ModelAttributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

// Attributes of a Cubic Model
type ModelAttributes struct {
	// Audio sample rate supported by the model
	SampleRate uint32 `protobuf:"varint,1,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	// If this is set to true, the model supports taking context information into
	// account to aid speech recognition. The information may be sent with with
	// recognition requests via RecognitionContext inside RecognitionConfig.
	SupportsContext bool `protobuf:"varint,2,opt,name=supports_context,json=supportsContext,proto3" json:"supports_context,omitempty"`
	// A list of tokens (e.g "names", "airports" etc.) that serve has placeholders
	// in the model where a client provided list of phrases or tokens may be used
	// to aid speech recognition and produce the exact desired recognition output.
	AllowedContextTokens []string `protobuf:"bytes,3,rep,name=allowed_context_tokens,json=allowedContextTokens,proto3" json:"allowed_context_tokens,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModelAttributes) Reset()         { *m = ModelAttributes{} }
func (m *ModelAttributes) String() string { return proto.CompactTextString(m) }
func (*ModelAttributes) ProtoMessage()    {}
func (*ModelAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_82ad8c6e2ec8aa3b, []int{15}
}

func (m *ModelAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelAttributes.Unmarshal(m, b)
}
func (m *ModelAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelAttributes.Marshal(b, m, deterministic)
}
func (m *ModelAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelAttributes.Merge(m, src)
}
func (m *ModelAttributes) XXX_Size() int {
	return xxx_messageInfo_ModelAttributes.Size(m)
}
func (m *ModelAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_ModelAttributes proto.InternalMessageInfo

func (m *ModelAttributes) GetSampleRate() uint32 {
	if m != nil {
		return m.SampleRate
	}
	return 0
}

func (m *ModelAttributes) GetSupportsContext() bool {
	if m != nil {
		return m.SupportsContext
	}
	return false
}

func (m *ModelAttributes) GetAllowedContextTokens() []string {
	if m != nil {
		return m.AllowedContextTokens
	}
	return nil
}

// A recognition result corresponding to a portion of audio.
type RecognitionResult struct {
	// An n-best list of recognition hypotheses alternatives
	Alternatives []*RecognitionAlternative `protobuf:"bytes,1,rep,name=alternatives,proto3" json:"alternatives,omitempty"`
	// If this is set to true, it denotes that the result is an interim partial
	// result, and could change after more audio is processed.  If unset, or set
	// to false, it denotes that this is a final result and will not change.
	//
	// Servers are not required to implement support for returning partial
	// results, and clients should generally not depend on their availability.
	IsPartial bool `protobuf:"varint,2,opt,name=is_partial,json=isPartial,proto3" json:"is_partial,omitempty"`
	// If `enable_confusion_network` was set to true in the `RecognitionConfig`,
	// and if the model supports it, a confusion network will be available in the
	// results.
	Cnet *RecognitionConfusionNetwork `protobuf:"bytes,3,opt,name=cnet,proto3" json:"cnet,omitempty"`
	// Channel of the audio file that this result was transcribed from.  For a
	// mono file, or RAW_LINEAR16 input, this will be set to 0.
	AudioChannel         uint32   `protobuf:"varint,4,opt,name=audio_channel,json=audioChannel,proto3" json:"audio_channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecognitionResult) Reset()         { *m = RecognitionResult{} }
func (m *RecognitionResult) String() string { return proto.CompactTextString(m) }
func (*RecognitionResult) ProtoMessage()    {}
func (*RecognitionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_82ad8c6e2ec8aa3b, []int{16}
}

func (m *RecognitionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecognitionResult.Unmarshal(m, b)
}
func (m *RecognitionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecognitionResult.Marshal(b, m, deterministic)
}
func (m *RecognitionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecognitionResult.Merge(m, src)
}
func (m *RecognitionResult) XXX_Size() int {
	return xxx_messageInfo_RecognitionResult.Size(m)
}
func (m *RecognitionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RecognitionResult.DiscardUnknown(m)
}

var xxx_messageInfo_RecognitionResult proto.InternalMessageInfo

func (m *RecognitionResult) GetAlternatives() []*RecognitionAlternative {
	if m != nil {
		return m.Alternatives
	}
	return nil
}

func (m *RecognitionResult) GetIsPartial() bool {
	if m != nil {
		return m.IsPartial
	}
	return false
}

func (m *RecognitionResult) GetCnet() *RecognitionConfusionNetwork {
	if m != nil {
		return m.Cnet
	}
	return nil
}

func (m *RecognitionResult) GetAudioChannel() uint32 {
	if m != nil {
		return m.AudioChannel
	}
	return 0
}

// A recognition hypothesis
type RecognitionAlternative struct {
	// Text representing the transcription of the words that the user spoke.
	//
	// The transcript will be formatted according to the servers formatting
	// configuration. If you want the raw transcript, please see the field
	// `raw_transcript`.  If the server is configured to not use any formatting,
	// then this field will contain the raw transcript.
	//
	// As an example, if the spoken utterance was "four people", and the
	// server was configured to format numbers, this field would be set to
	// "4 people".
	Transcript string `protobuf:"bytes,1,opt,name=transcript,proto3" json:"transcript,omitempty"`
	// Text representing the transcription of the words that the user spoke,
	// without any formatting.  This field will be populated only the config
	// `RecognitionConfig.enable_raw_transcript` is set to true. Otherwise this
	// field will be an empty string. If you want the formatted transcript, please
	// see the field `transcript`.
	//
	// As an example, if the spoken utterance was `here are four words`,
	// this field would be set to "HERE ARE FOUR WORDS".
	RawTranscript string `protobuf:"bytes,6,opt,name=raw_transcript,json=rawTranscript,proto3" json:"raw_transcript,omitempty"`
	// Confidence estimate between 0 and 1. A higher number represents a higher
	// likelihood of the output being correct.
	Confidence float64 `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// A list of word-specific information for each recognized word.  This is
	// available only if `enable_word_confidence` or `enable_word_time_offsets`
	// was set to `true` in the `RecognitionConfig`.
	Words []*WordInfo `protobuf:"bytes,3,rep,name=words,proto3" json:"words,omitempty"`
	// Time offset relative to the beginning of audio received by the recognizer
	// and corresponding to the start of this utterance.
	StartTime *duration.Duration `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Duration of the current utterance in the spoken audio.
	Duration             *duration.Duration `protobuf:"bytes,5,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RecognitionAlternative) Reset()         { *m = RecognitionAlternative{} }
func (m *RecognitionAlternative) String() string { return proto.CompactTextString(m) }
func (*RecognitionAlternative) ProtoMessage()    {}
func (*RecognitionAlternative) Descriptor() ([]byte, []int) {
	return fileDescriptor_82ad8c6e2ec8aa3b, []int{17}
}

func (m *RecognitionAlternative) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecognitionAlternative.Unmarshal(m, b)
}
func (m *RecognitionAlternative) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecognitionAlternative.Marshal(b, m, deterministic)
}
func (m *RecognitionAlternative) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecognitionAlternative.Merge(m, src)
}
func (m *RecognitionAlternative) XXX_Size() int {
	return xxx_messageInfo_RecognitionAlternative.Size(m)
}
func (m *RecognitionAlternative) XXX_DiscardUnknown() {
	xxx_messageInfo_RecognitionAlternative.DiscardUnknown(m)
}

var xxx_messageInfo_RecognitionAlternative proto.InternalMessageInfo

func (m *RecognitionAlternative) GetTranscript() string {
	if m != nil {
		return m.Transcript
	}
	return ""
}

func (m *RecognitionAlternative) GetRawTranscript() string {
	if m != nil {
		return m.RawTranscript
	}
	return ""
}

func (m *RecognitionAlternative) GetConfidence() float64 {
	if m != nil {
		return m.Confidence
	}
	return 0
}

func (m *RecognitionAlternative) GetWords() []*WordInfo {
	if m != nil {
		return m.Words
	}
	return nil
}

func (m *RecognitionAlternative) GetStartTime() *duration.Duration {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *RecognitionAlternative) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

// Word-specific information for recognized words
type WordInfo struct {
	// The actual word in the text
	Word string `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	// Confidence estimate between 0 and 1.  A higher number represents a
	// higher likelihood that the word was correctly recognized.
	Confidence float64 `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// Time offset relative to the beginning of audio received by the recognizer
	// and corresponding to the start of this spoken word.
	StartTime *duration.Duration `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Duration of the current word in the spoken audio.
	Duration             *duration.Duration `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *WordInfo) Reset()         { *m = WordInfo{} }
func (m *WordInfo) String() string { return proto.CompactTextString(m) }
func (*WordInfo) ProtoMessage()    {}
func (*WordInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_82ad8c6e2ec8aa3b, []int{18}
}

func (m *WordInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WordInfo.Unmarshal(m, b)
}
func (m *WordInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WordInfo.Marshal(b, m, deterministic)
}
func (m *WordInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WordInfo.Merge(m, src)
}
func (m *WordInfo) XXX_Size() int {
	return xxx_messageInfo_WordInfo.Size(m)
}
func (m *WordInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_WordInfo.DiscardUnknown(m)
}

var xxx_messageInfo_WordInfo proto.InternalMessageInfo

func (m *WordInfo) GetWord() string {
	if m != nil {
		return m.Word
	}
	return ""
}

func (m *WordInfo) GetConfidence() float64 {
	if m != nil {
		return m.Confidence
	}
	return 0
}

func (m *WordInfo) GetStartTime() *duration.Duration {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *WordInfo) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

// Confusion network in recognition output
type RecognitionConfusionNetwork struct {
	Links                []*ConfusionNetworkLink `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *RecognitionConfusionNetwork) Reset()         { *m = RecognitionConfusionNetwork{} }
func (m *RecognitionConfusionNetwork) String() string { return proto.CompactTextString(m) }
func (*RecognitionConfusionNetwork) ProtoMessage()    {}
func (*RecognitionConfusionNetwork) Descriptor() ([]byte, []int) {
	return fileDescriptor_82ad8c6e2ec8aa3b, []int{19}
}

func (m *RecognitionConfusionNetwork) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecognitionConfusionNetwork.Unmarshal(m, b)
}
func (m *RecognitionConfusionNetwork) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecognitionConfusionNetwork.Marshal(b, m, deterministic)
}
func (m *RecognitionConfusionNetwork) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecognitionConfusionNetwork.Merge(m, src)
}
func (m *RecognitionConfusionNetwork) XXX_Size() int {
	return xxx_messageInfo_RecognitionConfusionNetwork.Size(m)
}
func (m *RecognitionConfusionNetwork) XXX_DiscardUnknown() {
	xxx_messageInfo_RecognitionConfusionNetwork.DiscardUnknown(m)
}

var xxx_messageInfo_RecognitionConfusionNetwork proto.InternalMessageInfo

func (m *RecognitionConfusionNetwork) GetLinks() []*ConfusionNetworkLink {
	if m != nil {
		return m.Links
	}
	return nil
}

// A Link inside a confusion network
type ConfusionNetworkLink struct {
	// Time offset relative to the beginning of audio received by the recognizer
	// and corresponding to the start of this link
	StartTime *duration.Duration `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Duration of the current link in the confusion network
	Duration *duration.Duration `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	// Arcs between this link
	Arcs                 []*ConfusionNetworkArc `protobuf:"bytes,3,rep,name=arcs,proto3" json:"arcs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ConfusionNetworkLink) Reset()         { *m = ConfusionNetworkLink{} }
func (m *ConfusionNetworkLink) String() string { return proto.CompactTextString(m) }
func (*ConfusionNetworkLink) ProtoMessage()    {}
func (*ConfusionNetworkLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_82ad8c6e2ec8aa3b, []int{20}
}

func (m *ConfusionNetworkLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfusionNetworkLink.Unmarshal(m, b)
}
func (m *ConfusionNetworkLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfusionNetworkLink.Marshal(b, m, deterministic)
}
func (m *ConfusionNetworkLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfusionNetworkLink.Merge(m, src)
}
func (m *ConfusionNetworkLink) XXX_Size() int {
	return xxx_messageInfo_ConfusionNetworkLink.Size(m)
}
func (m *ConfusionNetworkLink) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfusionNetworkLink.DiscardUnknown(m)
}

var xxx_messageInfo_ConfusionNetworkLink proto.InternalMessageInfo

func (m *ConfusionNetworkLink) GetStartTime() *duration.Duration {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *ConfusionNetworkLink) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *ConfusionNetworkLink) GetArcs() []*ConfusionNetworkArc {
	if m != nil {
		return m.Arcs
	}
	return nil
}

// An Arc inside a Confusion Network Link
type ConfusionNetworkArc struct {
	// Word in the recognized transcript
	Word string `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	// Confidence estimate between 0 and 1.  A higher number represents a higher
	// likelihood that the word was correctly recognized.
	Confidence           float64  `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfusionNetworkArc) Reset()         { *m = ConfusionNetworkArc{} }
func (m *ConfusionNetworkArc) String() string { return proto.CompactTextString(m) }
func (*ConfusionNetworkArc) ProtoMessage()    {}
func (*ConfusionNetworkArc) Descriptor() ([]byte, []int) {
	return fileDescriptor_82ad8c6e2ec8aa3b, []int{21}
}

func (m *ConfusionNetworkArc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfusionNetworkArc.Unmarshal(m, b)
}
func (m *ConfusionNetworkArc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfusionNetworkArc.Marshal(b, m, deterministic)
}
func (m *ConfusionNetworkArc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfusionNetworkArc.Merge(m, src)
}
func (m *ConfusionNetworkArc) XXX_Size() int {
	return xxx_messageInfo_ConfusionNetworkArc.Size(m)
}
func (m *ConfusionNetworkArc) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfusionNetworkArc.DiscardUnknown(m)
}

var xxx_messageInfo_ConfusionNetworkArc proto.InternalMessageInfo

func (m *ConfusionNetworkArc) GetWord() string {
	if m != nil {
		return m.Word
	}
	return ""
}

func (m *ConfusionNetworkArc) GetConfidence() float64 {
	if m != nil {
		return m.Confidence
	}
	return 0
}

func init() {
	proto.RegisterEnum("cobaltspeech.cubic.RecognitionConfig_Encoding", RecognitionConfig_Encoding_name, RecognitionConfig_Encoding_value)
	proto.RegisterType((*ListModelsRequest)(nil), "cobaltspeech.cubic.ListModelsRequest")
	proto.RegisterType((*RecognizeRequest)(nil), "cobaltspeech.cubic.RecognizeRequest")
	proto.RegisterType((*StreamingRecognizeRequest)(nil), "cobaltspeech.cubic.StreamingRecognizeRequest")
	proto.RegisterType((*CompileContextRequest)(nil), "cobaltspeech.cubic.CompileContextRequest")
	proto.RegisterType((*VersionResponse)(nil), "cobaltspeech.cubic.VersionResponse")
	proto.RegisterType((*ListModelsResponse)(nil), "cobaltspeech.cubic.ListModelsResponse")
	proto.RegisterType((*RecognitionResponse)(nil), "cobaltspeech.cubic.RecognitionResponse")
	proto.RegisterType((*CompileContextResponse)(nil), "cobaltspeech.cubic.CompileContextResponse")
	proto.RegisterType((*RecognitionConfig)(nil), "cobaltspeech.cubic.RecognitionConfig")
	proto.RegisterType((*RecognitionMetadata)(nil), "cobaltspeech.cubic.RecognitionMetadata")
	proto.RegisterType((*RecognitionContext)(nil), "cobaltspeech.cubic.RecognitionContext")
	proto.RegisterType((*CompiledContext)(nil), "cobaltspeech.cubic.CompiledContext")
	proto.RegisterType((*ContextPhrase)(nil), "cobaltspeech.cubic.ContextPhrase")
	proto.RegisterType((*RecognitionAudio)(nil), "cobaltspeech.cubic.RecognitionAudio")
	proto.RegisterType((*Model)(nil), "cobaltspeech.cubic.Model")
	proto.RegisterType((*ModelAttributes)(nil), "cobaltspeech.cubic.ModelAttributes")
	proto.RegisterType((*RecognitionResult)(nil), "cobaltspeech.cubic.RecognitionResult")
	proto.RegisterType((*RecognitionAlternative)(nil), "cobaltspeech.cubic.RecognitionAlternative")
	proto.RegisterType((*WordInfo)(nil), "cobaltspeech.cubic.WordInfo")
	proto.RegisterType((*RecognitionConfusionNetwork)(nil), "cobaltspeech.cubic.RecognitionConfusionNetwork")
	proto.RegisterType((*ConfusionNetworkLink)(nil), "cobaltspeech.cubic.ConfusionNetworkLink")
	proto.RegisterType((*ConfusionNetworkArc)(nil), "cobaltspeech.cubic.ConfusionNetworkArc")
}

func init() { proto.RegisterFile("cubic.proto", fileDescriptor_82ad8c6e2ec8aa3b) }

var fileDescriptor_82ad8c6e2ec8aa3b = []byte{
	// 1379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xcd, 0x72, 0x1b, 0x45,
	0x10, 0xce, 0xea, 0xc7, 0x92, 0x5a, 0x3f, 0x56, 0x5a, 0x8e, 0x91, 0x9d, 0x60, 0xcc, 0x86, 0xc4,
	0x4e, 0xaa, 0x90, 0x1d, 0x27, 0x40, 0xc8, 0x9f, 0x51, 0x44, 0x20, 0xae, 0x72, 0x7e, 0x6a, 0x92,
	0xd8, 0x14, 0x05, 0xa5, 0x5a, 0xed, 0x8e, 0x9d, 0x2d, 0x4b, 0x3b, 0xcb, 0xee, 0x28, 0x06, 0x8e,
	0x14, 0x39, 0x72, 0xca, 0x23, 0x00, 0x17, 0x2e, 0xbc, 0x04, 0x6f, 0xc0, 0x13, 0x50, 0xc5, 0x91,
	0x87, 0xa0, 0xb6, 0x77, 0x66, 0x2d, 0x59, 0x8a, 0xa5, 0xf2, 0x6d, 0x67, 0xba, 0xbf, 0xee, 0x6f,
	0x66, 0xbb, 0xbf, 0x99, 0x81, 0xa2, 0xdd, 0xef, 0xb8, 0x76, 0xc3, 0x0f, 0x84, 0x14, 0x88, 0xb6,
	0xe8, 0x58, 0x5d, 0x19, 0xfa, 0x9c, 0xdb, 0x2f, 0x1b, 0x64, 0x59, 0xbc, 0xb0, 0x2f, 0xc4, 0x7e,
	0x97, 0xaf, 0x59, 0xbe, 0xbb, 0x66, 0x79, 0x9e, 0x90, 0x96, 0x74, 0x85, 0x17, 0xc6, 0x88, 0xc5,
	0x25, 0x65, 0xa5, 0x51, 0xa7, 0xbf, 0xb7, 0xe6, 0xf4, 0x03, 0x72, 0x50, 0xf6, 0xf3, 0xc7, 0xed,
	0xbc, 0xe7, 0xcb, 0x1f, 0x62, 0xa3, 0x59, 0x83, 0xb3, 0xdb, 0x6e, 0x28, 0x1f, 0x09, 0x87, 0x77,
	0x43, 0xc6, 0xbf, 0xeb, 0xf3, 0x50, 0x9a, 0xbf, 0x18, 0x50, 0x65, 0xdc, 0x16, 0xfb, 0x9e, 0xfb,
	0x23, 0x57, 0x93, 0x78, 0x17, 0x66, 0x6c, 0xe1, 0xed, 0xb9, 0xfb, 0x75, 0x63, 0xd9, 0x58, 0x2d,
	0x6e, 0x5c, 0x6a, 0x8c, 0x32, 0x6d, 0x28, 0x54, 0x94, 0xbd, 0x45, 0xce, 0x4c, 0x81, 0xf0, 0x16,
	0x64, 0xad, 0xbe, 0xe3, 0x8a, 0x7a, 0x8a, 0xd0, 0x1f, 0x4c, 0x40, 0x37, 0x23, 0x5f, 0x16, 0x43,
	0xcc, 0xdf, 0x0d, 0x58, 0x78, 0x26, 0x03, 0x6e, 0xf5, 0x5c, 0x6f, 0x7f, 0x84, 0xd8, 0xe6, 0xa9,
	0x88, 0x3d, 0x3c, 0x93, 0x50, 0xbb, 0x73, 0x0a, 0x6a, 0x0f, 0xcf, 0x28, 0x72, 0xf7, 0x0b, 0x90,
	0x0b, 0xd4, 0xbe, 0xbd, 0x36, 0xe0, 0x5c, 0x4b, 0xf4, 0x7c, 0xb7, 0xcb, 0x5b, 0xc2, 0x93, 0xfc,
	0x7b, 0xa9, 0x39, 0x2e, 0x40, 0xbe, 0x17, 0x6d, 0x71, 0xdb, 0x75, 0x88, 0x65, 0x81, 0xe5, 0x68,
	0xbc, 0xe5, 0xe0, 0x1c, 0x64, 0xa5, 0x38, 0xe0, 0x1e, 0x65, 0x2f, 0xb0, 0x78, 0x80, 0xb7, 0x21,
	0xe7, 0xbf, 0x0c, 0xac, 0x90, 0x87, 0xf5, 0xf4, 0x72, 0x7a, 0xb5, 0xb8, 0xf1, 0xfe, 0x38, 0x56,
	0x2a, 0xcb, 0x53, 0xf2, 0x64, 0x1a, 0x61, 0x6e, 0xc2, 0xec, 0x0e, 0x0f, 0x42, 0x57, 0x78, 0x8c,
	0x87, 0xbe, 0xf0, 0x42, 0x1e, 0x65, 0x21, 0x88, 0xca, 0x1e, 0x0f, 0x70, 0x1e, 0x66, 0x42, 0x1e,
	0xbc, 0xe2, 0x81, 0x4a, 0xae, 0x46, 0xe6, 0x97, 0x80, 0x83, 0x55, 0xa1, 0x62, 0x5c, 0x83, 0x19,
	0x22, 0x1d, 0xd6, 0x0d, 0xa2, 0xb4, 0x30, 0x8e, 0x12, 0x61, 0x98, 0x72, 0x34, 0x77, 0xa0, 0x36,
	0xb0, 0x73, 0x49, 0xa4, 0xcd, 0x68, 0xcf, 0xc2, 0x7e, 0x57, 0xea, 0x50, 0x93, 0xfe, 0x19, 0x23,
	0x6f, 0xa6, 0x51, 0xe6, 0x2e, 0xcc, 0x1f, 0xdf, 0x68, 0x15, 0xfa, 0x2e, 0xe4, 0xec, 0x78, 0x4a,
	0x95, 0xc3, 0xc5, 0xf1, 0x1b, 0x47, 0x60, 0x47, 0xa3, 0x35, 0xc6, 0xfc, 0x35, 0x0b, 0x67, 0x47,
	0x6a, 0xe5, 0xa4, 0xdf, 0xf7, 0x02, 0x2a, 0x54, 0x07, 0x6d, 0xee, 0xd9, 0xc2, 0x71, 0xbd, 0x7d,
	0xda, 0xca, 0xca, 0x46, 0x63, 0xaa, 0x2a, 0x6c, 0x3c, 0x50, 0x28, 0x56, 0xa6, 0x28, 0x7a, 0x88,
	0x77, 0xa0, 0xe4, 0x3a, 0x5d, 0xde, 0x96, 0x6e, 0x8f, 0x8b, 0xbe, 0xac, 0xa7, 0x69, 0x2d, 0x0b,
	0x8d, 0xb8, 0x97, 0x1b, 0xba, 0x97, 0x1b, 0x9f, 0xab, 0x5e, 0x67, 0xc5, 0xc8, 0xfd, 0x79, 0xec,
	0x8d, 0x9f, 0x40, 0x9d, 0x7b, 0x56, 0xa7, 0xcb, 0xdb, 0x87, 0x22, 0x70, 0x28, 0x48, 0x5b, 0xec,
	0xed, 0x85, 0x5c, 0x86, 0xf5, 0xcc, 0xb2, 0xb1, 0x9a, 0x67, 0xe7, 0x62, 0xfb, 0xae, 0x08, 0x9c,
	0x08, 0xf4, 0x24, 0x36, 0xe2, 0x0d, 0x98, 0x1f, 0x04, 0x52, 0x83, 0x38, 0xdc, 0xb3, 0x79, 0x3d,
	0x4b, 0xb0, 0xb9, 0x23, 0x58, 0x2b, 0xb1, 0xe1, 0x06, 0xa8, 0x70, 0xed, 0xc0, 0x3a, 0x6c, 0xcb,
	0xc0, 0xf2, 0x42, 0x3b, 0x70, 0x7d, 0x59, 0x9f, 0x21, 0x50, 0x2d, 0x36, 0x32, 0xeb, 0xf0, 0x79,
	0x62, 0xc2, 0x9b, 0x09, 0xc5, 0x28, 0x49, 0x3f, 0x2a, 0xd6, 0xb6, 0xc7, 0xe5, 0xa1, 0x08, 0x0e,
	0xea, 0x39, 0x82, 0x29, 0x26, 0x2d, 0x6d, 0x7e, 0x1c, 0x5b, 0xf1, 0x92, 0xde, 0x71, 0xfb, 0xa5,
	0xe5, 0x79, 0x51, 0x39, 0xe6, 0x97, 0xd3, 0xab, 0x65, 0xb5, 0x83, 0x2d, 0x35, 0x89, 0x2d, 0xc8,
	0xf7, 0xb8, 0xb4, 0x1c, 0x4b, 0x5a, 0xf5, 0x02, 0xed, 0xde, 0xca, 0x84, 0x5f, 0xf2, 0x48, 0xb9,
	0xb3, 0x04, 0x88, 0x9f, 0x1d, 0x55, 0x13, 0x50, 0x8c, 0xcb, 0x93, 0x7f, 0xeb, 0x70, 0x41, 0x3d,
	0x83, 0x7c, 0xf2, 0x53, 0xab, 0x50, 0x62, 0xcd, 0xdd, 0xf6, 0xf6, 0xd6, 0xe3, 0x07, 0x4d, 0x76,
	0xed, 0xe3, 0xea, 0x19, 0xcc, 0x41, 0x7a, 0xb7, 0xb9, 0x53, 0x35, 0xa2, 0x8f, 0x47, 0x4f, 0xaf,
	0x57, 0x53, 0x98, 0x87, 0xcc, 0x17, 0xdb, 0xcd, 0x56, 0x35, 0x8d, 0x45, 0xc8, 0xed, 0x3c, 0xf9,
	0xea, 0xe6, 0xfa, 0xfa, 0x7a, 0x35, 0x83, 0x25, 0xc8, 0xbf, 0xd8, 0x6e, 0xee, 0xd2, 0x28, 0x6b,
	0xde, 0x1b, 0x6a, 0x2b, 0xcd, 0x1b, 0x57, 0x60, 0xd6, 0xee, 0x87, 0x52, 0xf4, 0xda, 0xc9, 0xca,
	0xe3, 0x6a, 0xad, 0xc4, 0xd3, 0xda, 0xd1, 0x7c, 0x01, 0x38, 0xca, 0x19, 0x37, 0x21, 0xaf, 0x58,
	0xeb, 0xb6, 0x9c, 0xaa, 0x77, 0x12, 0x90, 0x79, 0x09, 0x66, 0x8f, 0x19, 0x11, 0x21, 0x43, 0x3c,
	0xa2, 0xa6, 0x28, 0x31, 0xfa, 0x36, 0x3f, 0x85, 0xf2, 0x90, 0x70, 0x45, 0x4e, 0x49, 0xc3, 0x16,
	0x18, 0x7d, 0x47, 0x82, 0xd5, 0x11, 0x22, 0x94, 0x84, 0x4c, 0xb1, 0x78, 0x60, 0x5e, 0x4e, 0x0e,
	0xa6, 0x44, 0x89, 0x93, 0x14, 0xc6, 0x40, 0x0a, 0x1f, 0xb2, 0x24, 0x44, 0x58, 0x81, 0x54, 0xd2,
	0xb3, 0x29, 0xd7, 0x89, 0x9c, 0x3d, 0xab, 0xc7, 0x95, 0xde, 0xd1, 0x37, 0xb6, 0x00, 0x2c, 0x29,
	0x03, 0xb7, 0xd3, 0x97, 0x24, 0xb7, 0x6f, 0x55, 0x0d, 0x0a, 0xd9, 0x4c, 0x5c, 0xd9, 0x00, 0xcc,
	0x7c, 0x63, 0xc0, 0xec, 0x31, 0x3b, 0xbe, 0x07, 0xc5, 0xd0, 0xea, 0xf9, 0xd4, 0x17, 0x92, 0x13,
	0x8b, 0x32, 0x83, 0x78, 0x8a, 0x59, 0x92, 0xe3, 0x15, 0xa8, 0x86, 0x7d, 0xdf, 0x17, 0x81, 0x0c,
	0xdb, 0xba, 0xce, 0x52, 0x54, 0xfc, 0xb3, 0x7a, 0x5e, 0x6f, 0xe4, 0x0d, 0x98, 0xb7, 0xba, 0x5d,
	0x71, 0xc8, 0x1d, 0xed, 0xd9, 0xa6, 0x93, 0x22, 0x3e, 0x1f, 0x0a, 0x6c, 0x4e, 0x59, 0x95, 0xff,
	0x73, 0xb2, 0x99, 0xff, 0x19, 0x43, 0x72, 0x16, 0xcb, 0x28, 0x3e, 0x86, 0x92, 0xd5, 0x95, 0x3c,
	0xf0, 0x2c, 0xe9, 0xbe, 0xe2, 0xfa, 0x67, 0x5f, 0x9d, 0x74, 0xee, 0x1d, 0x41, 0xd8, 0x10, 0x1e,
	0xdf, 0x05, 0x70, 0xc3, 0xb6, 0x6f, 0x05, 0xd2, 0xb5, 0xba, 0x6a, 0x01, 0x05, 0x37, 0x7c, 0x1a,
	0x4f, 0x60, 0x0b, 0x32, 0xb6, 0xc7, 0xb5, 0x86, 0xad, 0x4d, 0x21, 0x8c, 0x83, 0xfd, 0xce, 0x08,
	0x8c, 0x17, 0xa1, 0x3c, 0xd4, 0xf5, 0xa4, 0x63, 0x65, 0x56, 0x1a, 0x6c, 0x7a, 0xf3, 0xb7, 0x14,
	0xcc, 0x8f, 0x67, 0x8c, 0x4b, 0x00, 0x03, 0xc2, 0x14, 0x17, 0xc4, 0xc0, 0x4c, 0xa4, 0x2a, 0x63,
	0xc4, 0xab, 0xc0, 0xca, 0xc1, 0x90, 0x6c, 0x2d, 0x01, 0x0c, 0x88, 0x62, 0xb4, 0x54, 0x83, 0x0d,
	0xcc, 0xe0, 0x06, 0x64, 0x23, 0xe5, 0xd4, 0xa7, 0xf6, 0x85, 0x71, 0x8b, 0x8d, 0xd4, 0x73, 0xcb,
	0xdb, 0x13, 0x2c, 0x76, 0xc5, 0x9b, 0x00, 0xa1, 0xb4, 0x02, 0x49, 0x3a, 0x4d, 0xeb, 0x3a, 0x51,
	0xe9, 0x0b, 0xe4, 0x1c, 0xa9, 0x36, 0x7e, 0x04, 0x79, 0x7d, 0xd9, 0x23, 0x81, 0x3e, 0x11, 0x97,
	0xb8, 0x9a, 0x7f, 0x1a, 0x90, 0xd7, 0x24, 0xa2, 0x8e, 0x88, 0x68, 0xe8, 0xe6, 0x8b, 0xbe, 0x27,
	0xae, 0x72, 0x98, 0x71, 0xfa, 0x94, 0x8c, 0x33, 0xd3, 0x33, 0xfe, 0x16, 0xce, 0x9f, 0x50, 0x22,
	0x78, 0x0f, 0xb2, 0x5d, 0xd7, 0x3b, 0xd0, 0x95, 0xbc, 0xfa, 0x96, 0xbb, 0xd2, 0x10, 0x68, 0xdb,
	0xf5, 0x0e, 0x58, 0x0c, 0x33, 0xff, 0x32, 0x60, 0x6e, 0x9c, 0xfd, 0xd8, 0x42, 0x8d, 0x53, 0x2e,
	0x34, 0x35, 0xf5, 0x42, 0xf1, 0x36, 0x64, 0xac, 0xc0, 0xd6, 0xe5, 0xb3, 0x32, 0xcd, 0x42, 0x9a,
	0x81, 0xcd, 0x08, 0x64, 0x6e, 0x41, 0x6d, 0x8c, 0xf1, 0x34, 0x7f, 0x78, 0xe3, 0x9f, 0x0c, 0x64,
	0x5b, 0x74, 0x47, 0xfc, 0x06, 0x72, 0xea, 0x32, 0x89, 0xf3, 0x23, 0x2b, 0x78, 0x10, 0x3d, 0x25,
	0x16, 0xc7, 0x8a, 0xe5, 0xb1, 0x1b, 0xa8, 0x39, 0xf7, 0xd3, 0xdf, 0xff, 0xbe, 0x49, 0x55, 0xb0,
	0x44, 0xcf, 0x98, 0x57, 0x2a, 0xa4, 0x04, 0x38, 0xba, 0x69, 0xe2, 0xd8, 0x6b, 0xe0, 0xc8, 0xfb,
	0x64, 0xf1, 0xf2, 0x24, 0x37, 0x95, 0xf2, 0x1d, 0x4a, 0x79, 0x16, 0x67, 0x29, 0x65, 0xd7, 0x0d,
	0x65, 0x7c, 0x2d, 0xc5, 0x3e, 0x14, 0x92, 0x67, 0x04, 0x9e, 0x74, 0xdf, 0x4f, 0x5e, 0x19, 0x8b,
	0x2b, 0x93, 0x6f, 0xa8, 0x71, 0xd2, 0x05, 0x4a, 0x5a, 0x33, 0x2b, 0x94, 0x34, 0xd0, 0x71, 0x6e,
	0x19, 0x57, 0xf1, 0xb5, 0x01, 0x38, 0xfa, 0x8e, 0xc1, 0x0f, 0xc7, 0x85, 0x7e, 0xeb, 0x7b, 0x67,
	0x7a, 0x26, 0x35, 0x62, 0x52, 0xc6, 0x22, 0x31, 0x09, 0x29, 0xe0, 0xaa, 0xb1, 0x6e, 0xe0, 0xcf,
	0x06, 0x54, 0x86, 0xaf, 0xcf, 0x78, 0xe5, 0x84, 0x93, 0x7e, 0xf8, 0x2d, 0xb3, 0x78, 0x75, 0x1a,
	0x57, 0x45, 0xe1, 0x3c, 0x51, 0x38, 0x87, 0x35, 0xa2, 0x60, 0xc7, 0x4e, 0xea, 0xfc, 0xba, 0xbf,
	0xf4, 0x75, 0x8e, 0xc0, 0x7e, 0xe7, 0x8f, 0x14, 0xb6, 0x28, 0xe6, 0xb3, 0x38, 0x26, 0x55, 0x5e,
	0x67, 0x86, 0xca, 0xec, 0xfa, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x6d, 0x48, 0x4d, 0x20,
	0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CubicClient is the client API for Cubic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CubicClient interface {
	// Queries the Version of the Server
	Version(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
	// Retrieves a list of available speech recognition models
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	// Performs synchronous speech recognition: receive results after all audio
	// has been sent and processed.  It is expected that this request be typically
	// used for short audio content: less than a minute long.  For longer content,
	// the `StreamingRecognize` method should be preferred.
	Recognize(ctx context.Context, in *RecognizeRequest, opts ...grpc.CallOption) (*RecognitionResponse, error)
	// Performs bidirectional streaming speech recognition.  Receive results while
	// sending audio.  This method is only available via GRPC and not via
	// HTTP+JSON. However, a web browser may use websockets to use this service.
	StreamingRecognize(ctx context.Context, opts ...grpc.CallOption) (Cubic_StreamingRecognizeClient, error)
	// Compiles recognition context information, such as list of words or phrases
	// that may appear in the recognition output, into a compact, fast to access
	// form for a Cubic model. The compiled object may be sent with subsequent
	// `Recognize` or `StreamingRecognize` requests to aid speech recognition.
	// This is useful when the context information is constant for multiple
	// recognize requests. Precompiling context information like this ensures that
	// there is no added latency to recognition.
	CompileContext(ctx context.Context, in *CompileContextRequest, opts ...grpc.CallOption) (*CompileContextResponse, error)
}

type cubicClient struct {
	cc *grpc.ClientConn
}

func NewCubicClient(cc *grpc.ClientConn) CubicClient {
	return &cubicClient{cc}
}

func (c *cubicClient) Version(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/cobaltspeech.cubic.Cubic/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cubicClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, "/cobaltspeech.cubic.Cubic/ListModels", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cubicClient) Recognize(ctx context.Context, in *RecognizeRequest, opts ...grpc.CallOption) (*RecognitionResponse, error) {
	out := new(RecognitionResponse)
	err := c.cc.Invoke(ctx, "/cobaltspeech.cubic.Cubic/Recognize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cubicClient) StreamingRecognize(ctx context.Context, opts ...grpc.CallOption) (Cubic_StreamingRecognizeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Cubic_serviceDesc.Streams[0], "/cobaltspeech.cubic.Cubic/StreamingRecognize", opts...)
	if err != nil {
		return nil, err
	}
	x := &cubicStreamingRecognizeClient{stream}
	return x, nil
}

type Cubic_StreamingRecognizeClient interface {
	Send(*StreamingRecognizeRequest) error
	Recv() (*RecognitionResponse, error)
	grpc.ClientStream
}

type cubicStreamingRecognizeClient struct {
	grpc.ClientStream
}

func (x *cubicStreamingRecognizeClient) Send(m *StreamingRecognizeRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *cubicStreamingRecognizeClient) Recv() (*RecognitionResponse, error) {
	m := new(RecognitionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cubicClient) CompileContext(ctx context.Context, in *CompileContextRequest, opts ...grpc.CallOption) (*CompileContextResponse, error) {
	out := new(CompileContextResponse)
	err := c.cc.Invoke(ctx, "/cobaltspeech.cubic.Cubic/CompileContext", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CubicServer is the server API for Cubic service.
type CubicServer interface {
	// Queries the Version of the Server
	Version(context.Context, *empty.Empty) (*VersionResponse, error)
	// Retrieves a list of available speech recognition models
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	// Performs synchronous speech recognition: receive results after all audio
	// has been sent and processed.  It is expected that this request be typically
	// used for short audio content: less than a minute long.  For longer content,
	// the `StreamingRecognize` method should be preferred.
	Recognize(context.Context, *RecognizeRequest) (*RecognitionResponse, error)
	// Performs bidirectional streaming speech recognition.  Receive results while
	// sending audio.  This method is only available via GRPC and not via
	// HTTP+JSON. However, a web browser may use websockets to use this service.
	StreamingRecognize(Cubic_StreamingRecognizeServer) error
	// Compiles recognition context information, such as list of words or phrases
	// that may appear in the recognition output, into a compact, fast to access
	// form for a Cubic model. The compiled object may be sent with subsequent
	// `Recognize` or `StreamingRecognize` requests to aid speech recognition.
	// This is useful when the context information is constant for multiple
	// recognize requests. Precompiling context information like this ensures that
	// there is no added latency to recognition.
	CompileContext(context.Context, *CompileContextRequest) (*CompileContextResponse, error)
}

func RegisterCubicServer(s *grpc.Server, srv CubicServer) {
	s.RegisterService(&_Cubic_serviceDesc, srv)
}

func _Cubic_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubicServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cobaltspeech.cubic.Cubic/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubicServer).Version(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cubic_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubicServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cobaltspeech.cubic.Cubic/ListModels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubicServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cubic_Recognize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecognizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubicServer).Recognize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cobaltspeech.cubic.Cubic/Recognize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubicServer).Recognize(ctx, req.(*RecognizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cubic_StreamingRecognize_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CubicServer).StreamingRecognize(&cubicStreamingRecognizeServer{stream})
}

type Cubic_StreamingRecognizeServer interface {
	Send(*RecognitionResponse) error
	Recv() (*StreamingRecognizeRequest, error)
	grpc.ServerStream
}

type cubicStreamingRecognizeServer struct {
	grpc.ServerStream
}

func (x *cubicStreamingRecognizeServer) Send(m *RecognitionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *cubicStreamingRecognizeServer) Recv() (*StreamingRecognizeRequest, error) {
	m := new(StreamingRecognizeRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Cubic_CompileContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompileContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubicServer).CompileContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cobaltspeech.cubic.Cubic/CompileContext",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubicServer).CompileContext(ctx, req.(*CompileContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cubic_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cobaltspeech.cubic.Cubic",
	HandlerType: (*CubicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _Cubic_Version_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _Cubic_ListModels_Handler,
		},
		{
			MethodName: "Recognize",
			Handler:    _Cubic_Recognize_Handler,
		},
		{
			MethodName: "CompileContext",
			Handler:    _Cubic_CompileContext_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamingRecognize",
			Handler:       _Cubic_StreamingRecognize_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "cubic.proto",
}
