# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios-cubic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-cubic
  pod 'SwiftProtobuf', '~> 1.0'
  pod 'SwiftGRPC'
  target 'ios-cubicTests' do
    # Pods for testing
  end

end
